// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb.h for the primary calling header

#ifndef VERILATED_VTB___024ROOT_H_
#define VERILATED_VTB___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vtb__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        CData/*0:0*/ tb__DOT__ROM_CS;
        CData/*0:0*/ tb__DOT__flag;
        CData/*0:0*/ tb__DOT__WEb;
        CData/*0:0*/ tb__DOT__uprj__DOT__serial_ports__DOT____Vcellout__spi__SCLK;
        VL_IN8(rst_n,0,0);
        VL_IN8(wbs_stb_i,0,0);
        VL_IN8(wbs_cyc_i,0,0);
        VL_IN8(wbs_we_i,0,0);
        VL_OUT8(wbs_ack_o,0,0);
        CData/*0:0*/ tb__DOT__SDO;
        CData/*0:0*/ tb__DOT__SDI;
        CData/*7:0*/ tb__DOT__bus_out;
        CData/*1:0*/ tb__DOT__uart_init_state;
        CData/*0:0*/ tb__DOT____Vtriunconn2;
        CData/*0:0*/ tb__DOT____Vtriunconn4;
        CData/*0:0*/ tb__DOT__uprj__DOT__reset;
        CData/*0:0*/ tb__DOT__uprj__DOT__irq0;
        CData/*0:0*/ tb__DOT__uprj__DOT__irq1;
        CData/*0:0*/ tb__DOT__uprj__DOT__irq2;
        CData/*0:0*/ tb__DOT__uprj__DOT__irq3;
        CData/*0:0*/ tb__DOT__uprj__DOT__irq5;
        CData/*0:0*/ tb__DOT__uprj__DOT__irq6;
        CData/*0:0*/ tb__DOT__uprj__DOT__irq7;
        CData/*7:0*/ tb__DOT__uprj__DOT__bus_data_out;
        CData/*7:0*/ tb__DOT__uprj__DOT__bus_data_gpios;
        CData/*0:0*/ tb__DOT__uprj__DOT__bus_cyc;
        CData/*0:0*/ tb__DOT__uprj__DOT__bus_we_gpios;
        CData/*7:0*/ tb__DOT__uprj__DOT__bus_data_timers;
        CData/*0:0*/ tb__DOT__uprj__DOT__bus_we_timers;
        CData/*7:0*/ tb__DOT__uprj__DOT__bus_data_serial_ports;
        CData/*0:0*/ tb__DOT__uprj__DOT__bus_we_serial_ports;
        CData/*7:0*/ tb__DOT__uprj__DOT__bus_data_sid;
        CData/*0:0*/ tb__DOT__uprj__DOT__bus_we_sid;
        CData/*0:0*/ tb__DOT__uprj__DOT__le_lo_act;
        CData/*0:0*/ tb__DOT__uprj__DOT__le_hi_act;
        CData/*2:0*/ tb__DOT__uprj__DOT__cs_port;
        CData/*0:0*/ tb__DOT__uprj__DOT__ram_enabled;
        CData/*6:0*/ tb__DOT__uprj__DOT____Vcellinp__wrapped_as2650__irqs;
        CData/*0:0*/ tb__DOT__uprj__DOT__tmr0_o;
        CData/*0:0*/ tb__DOT__uprj__DOT__tmr1_o;
        CData/*0:0*/ tb__DOT__uprj__DOT__RXD;
        CData/*0:0*/ tb__DOT__uprj__DOT__tmr0_clk;
        CData/*0:0*/ tb__DOT__uprj__DOT__tmr1_clk;
        CData/*0:0*/ tb__DOT__uprj__DOT__DAC_clk;
        CData/*7:0*/ tb__DOT__uprj__DOT____Vcellout__gpios__la_data_out;
        CData/*7:0*/ tb__DOT__uprj__DOT__Q0;
        CData/*7:0*/ tb__DOT__uprj__DOT__Q1;
        CData/*7:0*/ tb__DOT__uprj__DOT__Q2;
        CData/*7:0*/ tb__DOT__uprj__DOT__Q3;
        CData/*7:0*/ tb__DOT__uprj__DOT__Q4;
        CData/*7:0*/ tb__DOT__uprj__DOT__Q5;
        CData/*7:0*/ tb__DOT__uprj__DOT__Q6;
        CData/*7:0*/ tb__DOT__uprj__DOT__Q7;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__wb_ready;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__wb_feedback_delay;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__wb_valid;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__wb_debug_cc;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__wb_debug_carry;
        CData/*1:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__web_behavior;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__wb_reset_override_en;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__wb_reset_override;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__wb_io3_test;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__wb_io3_state;
    };
    struct {
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__wb_hidden_rom_enable;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__cpu_hidden_rom_enable;
        CData/*7:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__full_io_addr;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__io_bus_we;
        CData/*7:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__bus_in_plexed;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__in_ram_range;
        CData/*7:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__bus_in;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__trap;
        CData/*7:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__irqs_latch;
        CData/*2:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__irq_num;
        CData/*7:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__psu;
        CData/*7:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__psl;
        CData/*2:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__page_reg;
        CData/*3:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__cycle;
        CData/*7:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__insin;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__extend;
        CData/*1:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__warmup;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__indirect_cyc;
        CData/*1:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__indexed_cyc;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__relative_cyc;
        CData/*7:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__instruction;
        CData/*7:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__index;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_interrupt_cycle;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_instr_fetch_cycle;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__IO_cyc;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_RETURN;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_DAR;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_CLR;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_EXT;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_HALT;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_NOP;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_XCHG;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_MUL;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_ZBR;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_BXA;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_LPS;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_SPS;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__needs_param;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__needs_2_param;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_indexed;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_indirect_p1;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_indirect_p2;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_store;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_COM;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_ALU_op;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_add_sub;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_PUSH;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_POP;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_TPS;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_CPS;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_PPS;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_RRR;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_RRL;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_TMI;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_IO_READ;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_IO_WRITE;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_CPL;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_PSHS;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_POPS;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_SVB;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_CHRP;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_EXT_IO;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_TRAP;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_CLRT;
    };
    struct {
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_LIR;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_SIR;
        CData/*2:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__instr_reg_a;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_CC_BRANCH;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__is_BRANCH_SUB;
        CData/*7:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__branch_compare_reg;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__should_branch;
        CData/*2:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__r0_a;
        CData/*2:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__r1_a;
        CData/*7:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__rrr;
        CData/*7:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__rrl;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__indexed_data1;
        CData/*7:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__alu_instr_reg;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__next_idc;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__next_ovf;
        CData/*2:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__chirp_ptr;
        CData/*6:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__chirpchar;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT____VdfgTmp_h67c18dcd__0;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT____VdfgTmp_h0482dd45__0;
        CData/*7:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT____VdfgTmp_hc49c8b73__0;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT____VdfgTmp_h5a2433b0__0;
        CData/*0:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT____VdfgTmp_h06a17774__0;
        CData/*7:0*/ tb__DOT__uprj__DOT__gpios__DOT__DDRA;
        CData/*7:0*/ tb__DOT__uprj__DOT__gpios__DOT__DDRB;
        CData/*7:0*/ tb__DOT__uprj__DOT__gpios__DOT__PORTA;
        CData/*7:0*/ tb__DOT__uprj__DOT__gpios__DOT__PORTB;
        CData/*7:0*/ tb__DOT__uprj__DOT__gpios__DOT__SPA;
        CData/*7:0*/ tb__DOT__uprj__DOT__gpios__DOT__SPB;
        CData/*0:0*/ tb__DOT__uprj__DOT__gpios__DOT__last_irq0_trigger;
        CData/*0:0*/ tb__DOT__uprj__DOT__gpios__DOT__last_irg6_trigger;
        CData/*0:0*/ tb__DOT__uprj__DOT__gpios__DOT__last_irq7_trigger;
        CData/*0:0*/ tb__DOT__uprj__DOT__gpios__DOT__irq0_trigger;
        CData/*0:0*/ tb__DOT__uprj__DOT__gpios__DOT__irq6_trigger;
        CData/*0:0*/ tb__DOT__uprj__DOT__gpios__DOT__irq7_trigger;
        CData/*2:0*/ tb__DOT__uprj__DOT__timers__DOT__settings;
        CData/*0:0*/ tb__DOT__uprj__DOT__timers__DOT__tmr0_ext;
        CData/*0:0*/ tb__DOT__uprj__DOT__timers__DOT__tmr1_ext;
        CData/*0:0*/ tb__DOT__uprj__DOT__timers__DOT__last_tmr0_clk;
        CData/*0:0*/ tb__DOT__uprj__DOT__timers__DOT__last_tmr1_clk;
        CData/*7:0*/ tb__DOT__uprj__DOT__timers__DOT__pwm_ctr0;
        CData/*7:0*/ tb__DOT__uprj__DOT__timers__DOT__pwm_ctr1;
        CData/*7:0*/ tb__DOT__uprj__DOT__timers__DOT__pwm_ctr2;
        CData/*7:0*/ tb__DOT__uprj__DOT__timers__DOT__pw0;
        CData/*7:0*/ tb__DOT__uprj__DOT__timers__DOT__pw1;
        CData/*7:0*/ tb__DOT__uprj__DOT__timers__DOT__pw2;
        CData/*7:0*/ tb__DOT__uprj__DOT__timers__DOT__temp;
        CData/*0:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__uart_ien;
        CData/*0:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__uart_busy;
        CData/*0:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__uart_has_byte;
        CData/*7:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__spi_div;
        CData/*7:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__uart_rec_byte;
        CData/*7:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__spi_rec_byte;
        CData/*0:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__spi_busy;
        CData/*0:0*/ tb__DOT__uprj__DOT__serial_ports__DOT____Vcellinp__uart__start;
        CData/*0:0*/ tb__DOT__uprj__DOT__serial_ports__DOT____Vcellinp__spi__start;
        CData/*0:0*/ tb__DOT__uprj__DOT__serial_ports__DOT____Vcellout__spi__DO;
        CData/*3:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__uart__DOT__counter;
        CData/*0:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__uart__DOT__receiving;
        CData/*7:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__uart__DOT__receive_buff;
        CData/*3:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__uart__DOT__receive_counter;
        CData/*7:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__spi__DOT__data_out_buff;
        CData/*7:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__spi__DOT__data_in_buff;
        CData/*7:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__spi__DOT__div_counter;
        CData/*4:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__spi__DOT__counter;
    };
    struct {
        CData/*7:0*/ tb__DOT__uprj__DOT__boot_rom__DOT__rom_data;
        CData/*7:0*/ tb__DOT__uprj__DOT__sid__DOT__read_res;
        CData/*7:0*/ tb__DOT__uprj__DOT__sid__DOT__ctrl_1;
        CData/*7:0*/ tb__DOT__uprj__DOT__sid__DOT__atk_dec_1;
        CData/*7:0*/ tb__DOT__uprj__DOT__sid__DOT__sus_rel_1;
        CData/*7:0*/ tb__DOT__uprj__DOT__sid__DOT__ctrl_2;
        CData/*7:0*/ tb__DOT__uprj__DOT__sid__DOT__atk_dec_2;
        CData/*7:0*/ tb__DOT__uprj__DOT__sid__DOT__sus_rel_2;
        CData/*7:0*/ tb__DOT__uprj__DOT__sid__DOT__ctrl_3;
        CData/*7:0*/ tb__DOT__uprj__DOT__sid__DOT__atk_dec_3;
        CData/*7:0*/ tb__DOT__uprj__DOT__sid__DOT__sus_rel_3;
        CData/*7:0*/ tb__DOT__uprj__DOT__sid__DOT__res_filt;
        CData/*7:0*/ tb__DOT__uprj__DOT__sid__DOT__mode_vol;
        CData/*1:0*/ tb__DOT__uprj__DOT__sid__DOT__clk_ctr;
        CData/*1:0*/ tb__DOT__uprj__DOT__sid__DOT__clk_trg;
        CData/*0:0*/ tb__DOT__uprj__DOT__sid__DOT__enable;
        CData/*0:0*/ tb__DOT__uprj__DOT__sid__DOT____Vcellinp__tt_um_rejunity_sn76489__we;
        CData/*7:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT__curr_ctrl_reg;
        CData/*7:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT__curr_atk_dec;
        CData/*7:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT__curr_sus_rel;
        CData/*0:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT__curr_ring_in;
        CData/*0:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT__curr_sync_in;
        CData/*4:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT__exp_period;
        CData/*2:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT__clk_div;
        CData/*1:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT__curr_channel;
        CData/*0:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT__env_top;
        CData/*0:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_hb3170973__0;
        CData/*0:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_he328b697__0;
        CData/*0:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_he755b0f5__0;
        CData/*4:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_h7da9ad18__0;
        CData/*1:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_h0f3908ee__0;
        CData/*7:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_h53c571ef__0;
        CData/*1:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_h0f3908ee__1;
        CData/*7:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_h53c571ef__1;
        CData/*7:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_h53c571ef__2;
        CData/*1:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_h0f3908ee__2;
        CData/*4:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_h51de987e__0;
        CData/*4:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_h51de987e__1;
        CData/*4:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_h51de987e__2;
        CData/*4:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_h51de987e__3;
        CData/*4:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_h51de987e__4;
        CData/*4:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_h51de987e__5;
        CData/*4:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_h51de987e__6;
        CData/*4:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_h51de987e__7;
        CData/*2:0*/ tb__DOT__uprj__DOT__sid__DOT__filters__DOT__filter_step;
        CData/*5:0*/ tb__DOT__uprj__DOT__sid__DOT__spi_dac_i__DOT__counter;
        CData/*4:0*/ tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT__clk_counter;
        CData/*2:0*/ tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT__latch_control_reg;
        CData/*0:0*/ tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT__restart_noise;
        CData/*0:0*/ tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT__tone__BRA__0__KET____DOT__gen__DOT__state;
        CData/*0:0*/ tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT__tone__BRA__1__KET____DOT__gen__DOT__state;
        CData/*0:0*/ tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT__tone__BRA__2__KET____DOT__gen__DOT__state;
        CData/*0:0*/ tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT__noise__BRA__0__KET____DOT__gen__DOT__trigger;
        CData/*6:0*/ tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT__noise__BRA__0__KET____DOT__gen__DOT__counter;
        CData/*0:0*/ tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT__noise__BRA__0__KET____DOT__gen__DOT__signal_edge__DOT__previous_signal_state_0;
        CData/*7:0*/ tb__DOT__uprj__DOT__ram_controller__DOT__curr_Q;
        CData/*0:0*/ tb__DOT__uprj__DOT__ram_controller__DOT____VdfgTmp_h69944c46__0;
        CData/*7:0*/ tb__DOT__spiflash__DOT__buffer;
        CData/*3:0*/ tb__DOT__spiflash__DOT__reset_count;
        CData/*3:0*/ tb__DOT__spiflash__DOT__reset_monitor;
        CData/*7:0*/ tb__DOT__spiflash__DOT__spi_cmd;
        CData/*7:0*/ tb__DOT__spiflash__DOT__xip_cmd;
        CData/*0:0*/ tb__DOT__spiflash__DOT__powered_up;
        CData/*3:0*/ tb__DOT__spiflash__DOT__mode;
    };
    struct {
        CData/*3:0*/ tb__DOT__spiflash__DOT__next_mode;
        CData/*0:0*/ tb__DOT__spiflash__DOT__io0_oe;
        CData/*0:0*/ tb__DOT__spiflash__DOT__io1_oe;
        CData/*0:0*/ tb__DOT__spiflash__DOT__io2_oe;
        CData/*0:0*/ tb__DOT__spiflash__DOT__io3_oe;
        CData/*0:0*/ tb__DOT__spiflash__DOT__io0_dout;
        CData/*0:0*/ tb__DOT__spiflash__DOT__io1_dout;
        CData/*0:0*/ tb__DOT__spiflash__DOT__io2_dout;
        CData/*0:0*/ tb__DOT__spiflash__DOT__io3_dout;
        CData/*1:0*/ __VdfgTmp_he37690df__0;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb__DOT__ROM_CS__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb__DOT__uprj__DOT__serial_ports__DOT____Vcellout__spi__SCLK__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb__DOT__flag__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb__DOT__WEb__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ tb__DOT__uprj__DOT__RAM_start_addr;
        SData/*15:0*/ tb__DOT__uprj__DOT__RAM_end_addr;
        SData/*15:0*/ tb__DOT__uprj__DOT__requested_addr;
        SData/*15:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__TOS;
        SData/*12:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__PC;
        SData/*11:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__ivectors_base;
        SData/*15:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__last_addr;
        SData/*15:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__instruction_args_latch;
        SData/*15:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__indirect_target;
        SData/*15:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__relative_eff_address;
        SData/*15:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__zbr_target;
        SData/*15:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__mul_res;
        SData/*8:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__alu_next;
        SData/*15:0*/ tb__DOT__uprj__DOT__timers__DOT__timer0;
        SData/*15:0*/ tb__DOT__uprj__DOT__timers__DOT__timer1;
        SData/*15:0*/ tb__DOT__uprj__DOT__timers__DOT__timer2;
        SData/*15:0*/ tb__DOT__uprj__DOT__timers__DOT__t0_capture;
        SData/*15:0*/ tb__DOT__uprj__DOT__timers__DOT__t1_capture;
        SData/*15:0*/ tb__DOT__uprj__DOT__timers__DOT__t2_capture;
        SData/*15:0*/ tb__DOT__uprj__DOT__timers__DOT__t0pre;
        SData/*15:0*/ tb__DOT__uprj__DOT__timers__DOT__t1pre;
        SData/*15:0*/ tb__DOT__uprj__DOT__timers__DOT__t2pre;
        SData/*15:0*/ tb__DOT__uprj__DOT__timers__DOT__t0pre_counter;
        SData/*15:0*/ tb__DOT__uprj__DOT__timers__DOT__t1pre_counter;
        SData/*15:0*/ tb__DOT__uprj__DOT__timers__DOT__t2pre_counter;
        SData/*15:0*/ tb__DOT__uprj__DOT__timers__DOT__t0_top;
        SData/*15:0*/ tb__DOT__uprj__DOT__timers__DOT__t1_top;
        SData/*15:0*/ tb__DOT__uprj__DOT__timers__DOT__t2_top;
        SData/*15:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__uart_div;
        SData/*9:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__uart__DOT__data_buff;
        SData/*15:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__uart__DOT__div_counter;
        SData/*15:0*/ tb__DOT__uprj__DOT__serial_ports__DOT__uart__DOT__receive_div_counter;
        SData/*15:0*/ tb__DOT__uprj__DOT__sid__DOT__freq_1;
        SData/*11:0*/ tb__DOT__uprj__DOT__sid__DOT__pw_1;
        SData/*15:0*/ tb__DOT__uprj__DOT__sid__DOT__freq_2;
        SData/*11:0*/ tb__DOT__uprj__DOT__sid__DOT__pw_2;
        SData/*15:0*/ tb__DOT__uprj__DOT__sid__DOT__freq_3;
        SData/*11:0*/ tb__DOT__uprj__DOT__sid__DOT__pw_3;
        SData/*10:0*/ tb__DOT__uprj__DOT__sid__DOT__fc;
        SData/*15:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT__curr_freq;
        SData/*11:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT__curr_pw;
        SData/*11:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_h19bf6dd8__0;
        SData/*14:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_hd92f9416__0;
        SData/*14:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_hd92f9416__1;
        SData/*14:0*/ tb__DOT__uprj__DOT__sid__DOT__filters__DOT__sample_buff;
    };
    struct {
        SData/*14:0*/ tb__DOT__uprj__DOT__sid__DOT__filters__DOT__sample_buff_next;
        SData/*11:0*/ tb__DOT__uprj__DOT__sid__DOT__spi_dac_i__DOT__spi_dat_buff_0;
        SData/*11:0*/ tb__DOT__uprj__DOT__sid__DOT__spi_dac_i__DOT__spi_dat_buff_1;
        SData/*9:0*/ tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT____Vcellout__chan__BRA__0__KET____DOT__attenuation__out;
        SData/*9:0*/ tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT____Vcellout__chan__BRA__1__KET____DOT__attenuation__out;
        SData/*9:0*/ tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT____Vcellout__chan__BRA__2__KET____DOT__attenuation__out;
        SData/*9:0*/ tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT____Vcellout__chan__BRA__3__KET____DOT__attenuation__out;
        SData/*9:0*/ tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT__tone__BRA__0__KET____DOT__gen__DOT__counter;
        SData/*9:0*/ tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT__tone__BRA__1__KET____DOT__gen__DOT__counter;
        SData/*9:0*/ tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT__tone__BRA__2__KET____DOT__gen__DOT__counter;
        SData/*14:0*/ tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT__noise__BRA__0__KET____DOT__gen__DOT__lfsr;
        SData/*15:0*/ tb__DOT__uprj__DOT__ram_controller__DOT__requested_addr_latch;
        VL_IN(wbs_dat_i,31,0);
        VL_IN(wbs_adr_i,31,0);
        VL_OUT(wbs_dat_o,31,0);
        IData/*31:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__wbs_o_buff;
        IData/*31:0*/ tb__DOT__uprj__DOT__wrapped_as2650__DOT__wb_counter;
        IData/*23:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT__accum_next;
        IData/*19:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT__mul_sample;
        IData/*23:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_hd2232b2a__0;
        IData/*21:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____Vlvbound_h44b3a740__0;
        IData/*22:0*/ tb__DOT__uprj__DOT__sid__DOT__channels__DOT____VdfgTmp_h36ba4a2e__0;
        IData/*31:0*/ tb__DOT__uprj__DOT__sid__DOT__filters__DOT__high;
        IData/*31:0*/ tb__DOT__uprj__DOT__sid__DOT__filters__DOT__band;
        IData/*31:0*/ tb__DOT__uprj__DOT__sid__DOT__filters__DOT__low;
        IData/*31:0*/ tb__DOT__uprj__DOT__sid__DOT__filters__DOT__band_low_next;
        IData/*31:0*/ tb__DOT__uprj__DOT__sid__DOT__filters__DOT__high_next;
        IData/*31:0*/ tb__DOT__uprj__DOT__sid__DOT__filters__DOT__sample_filtered;
        IData/*31:0*/ tb__DOT__uprj__DOT__sid__DOT__filters__DOT__sample_filtered_next;
        IData/*31:0*/ tb__DOT__spiflash__DOT__bitcount;
        IData/*31:0*/ tb__DOT__spiflash__DOT__bytecount;
        IData/*31:0*/ tb__DOT__spiflash__DOT__dummycount;
        IData/*23:0*/ tb__DOT__spiflash__DOT__spi_addr;
        IData/*31:0*/ __VactIterCount;
        QData/*37:0*/ tb__DOT__io_in;
        VlUnpacked<CData/*7:0*/, 8> tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__regs;
        VlUnpacked<SData/*15:0*/, 16> tb__DOT__uprj__DOT__wrapped_as2650__DOT__as2650__DOT__stack;
        VlUnpacked<SData/*11:0*/, 3> tb__DOT__uprj__DOT__sid__DOT__channels__DOT__samples;
        VlUnpacked<CData/*0:0*/, 3> tb__DOT__uprj__DOT__sid__DOT__channels__DOT__ring_outs;
        VlUnpacked<CData/*0:0*/, 3> tb__DOT__uprj__DOT__sid__DOT__channels__DOT__sync_outs;
        VlUnpacked<IData/*22:0*/, 3> tb__DOT__uprj__DOT__sid__DOT__channels__DOT__lfsr;
        VlUnpacked<IData/*23:0*/, 3> tb__DOT__uprj__DOT__sid__DOT__channels__DOT__accum;
        VlUnpacked<CData/*7:0*/, 3> tb__DOT__uprj__DOT__sid__DOT__channels__DOT__env_vol;
        VlUnpacked<CData/*4:0*/, 3> tb__DOT__uprj__DOT__sid__DOT__channels__DOT__exp_counter;
        VlUnpacked<SData/*14:0*/, 3> tb__DOT__uprj__DOT__sid__DOT__channels__DOT__env_counter;
        VlUnpacked<CData/*1:0*/, 3> tb__DOT__uprj__DOT__sid__DOT__channels__DOT__adsr_state;
        VlUnpacked<CData/*4:0*/, 3> tb__DOT__uprj__DOT__sid__DOT__channels__DOT__exp_periods;
        VlUnpacked<CData/*3:0*/, 4> tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT__control_attn;
        VlUnpacked<SData/*9:0*/, 3> tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT__control_tone_freq;
        VlUnpacked<CData/*2:0*/, 1> tb__DOT__uprj__DOT__sid__DOT__tt_um_rejunity_sn76489__DOT__control_noise;
        VlUnpacked<CData/*7:0*/, 512> tb__DOT__uprj__DOT__sram0__DOT__sram512x8__DOT__memory;
        VlUnpacked<CData/*7:0*/, 512> tb__DOT__uprj__DOT__sram1__DOT__sram512x8__DOT__memory;
        VlUnpacked<CData/*7:0*/, 512> tb__DOT__uprj__DOT__sram2__DOT__sram512x8__DOT__memory;
        VlUnpacked<CData/*7:0*/, 512> tb__DOT__uprj__DOT__sram3__DOT__sram512x8__DOT__memory;
        VlUnpacked<CData/*7:0*/, 512> tb__DOT__uprj__DOT__sram4__DOT__sram512x8__DOT__memory;
        VlUnpacked<CData/*7:0*/, 512> tb__DOT__uprj__DOT__sram5__DOT__sram512x8__DOT__memory;
        VlUnpacked<CData/*7:0*/, 512> tb__DOT__uprj__DOT__sram6__DOT__sram512x8__DOT__memory;
        VlUnpacked<CData/*7:0*/, 512> tb__DOT__uprj__DOT__sram7__DOT__sram512x8__DOT__memory;
        VlUnpacked<CData/*7:0*/, 16777216> tb__DOT__spiflash__DOT__memory;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<7> __VactTriggered;
    VlTriggerVec<7> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtb__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtb___024root(Vtb__Syms* symsp, const char* v__name);
    ~Vtb___024root();
    VL_UNCOPYABLE(Vtb___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
